"""Walking Deck builder.

Reads a config (brand + ordered, selectable slide blocks) and a content file,
then renders only the selected blocks into a 16:9 PowerPoint. Missing content
degrades gracefully so any project can pick just the slides it needs.

Usage:
    python scripts/build_deck.py --config config/walking-deck-config.json
    python scripts/build_deck.py --config <cfg> --content <content> --out <file.pptx>
    python scripts/build_deck.py --list-blocks
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from collections import Counter
from pathlib import Path
from zipfile import ZipFile

from pptx import Presentation
from pptx.util import Emu

sys.path.insert(0, str(Path(__file__).resolve().parent))
import deck_blocks as db  # noqa: E402

SLIDE_W = Emu(12192000)  # 13.333in
SLIDE_H = Emu(6858000)   # 7.5in


def _load(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def _blank_layout(prs: Presentation):
    for layout in prs.slide_layouts:
        if layout.name.lower() == "blank":
            return layout
    return prs.slide_layouts[6]


def _resolve_out(config: dict, cfg_dir: Path, override: str | None) -> Path:
    if override:
        return Path(override)
    out = config.get("output", {})
    folder = out.get("folder", "output")
    slug = config.get("project_slug", "walking-deck")
    stamp = dt.date.today().strftime("%Y%m%d")
    name = out.get("filename", "{slug}_Walking_Deck_{date}.pptx")
    name = name.replace("{date}", stamp).replace("{slug}", slug)
    base = (cfg_dir / folder) if not Path(folder).is_absolute() else Path(folder)
    base.mkdir(parents=True, exist_ok=True)
    return base / name


def build(config_path: Path, content_path: Path | None, out_override: str | None) -> Path:
    config = _load(config_path)
    cfg_dir = config_path.resolve().parent.parent  # package root (config/ is under it)

    content_file = content_path or (cfg_dir / config.get("content_file", "config/walking-deck-content.json"))
    content = _load(Path(content_file))
    meta = content.get("meta", {})

    brand_data = dict(config.get("brand", {}))
    for key in ("logo_path", "hero_path"):
        val = brand_data.get(key)
        if val and not Path(val).is_absolute():
            resolved = (cfg_dir / val)
            brand_data[key] = str(resolved) if resolved.exists() else None
    brand = db.Brand.from_dict(brand_data)

    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H
    blank = _blank_layout(prs)

    footer = meta.get("footer", "")
    selected = config.get("slides", [])
    if not selected:
        raise SystemExit("Config 'slides' is empty; select at least one block id.")

    page = 0
    unknown = []
    for entry in selected:
        if isinstance(entry, str):
            block_id, block_content = entry, None
        elif isinstance(entry, dict):
            block_id = entry.get("block")
            block_content = entry.get("content")
            if block_content is None and entry.get("content_key"):
                block_content = content.get(entry["content_key"])
        else:
            continue
        renderer = db.REGISTRY.get(block_id)
        if renderer is None:
            unknown.append(block_id)
            continue
        if block_content is None:
            block_content = content.get(block_id, {})
        page += 1
        ctx = db.Ctx(brand=brand, page=page, footer=footer,
                     body_font=brand.body_font, title_font=brand.title_font)
        slide = prs.slides.add_slide(blank)
        renderer(slide, ctx, block_content or {})

    if unknown:
        raise SystemExit(f"Unknown block id(s): {', '.join(unknown)}. Valid: {', '.join(db.BLOCK_IDS)}")

    props = prs.core_properties
    props.title = meta.get("title", "Walking Deck")
    props.subject = meta.get("subtitle", "")
    props.author = meta.get("author", "")
    props.comments = meta.get("comments", "Generated by the Walking Deck Agent.")

    out_path = _resolve_out(config, cfg_dir, out_override)
    prs.save(out_path)

    with ZipFile(out_path) as z:
        dupes = [n for n, c in Counter(z.namelist()).items() if c > 1]
    if dupes:
        raise SystemExit(f"Package integrity error: duplicate parts {dupes}")

    print(f"Created {out_path}")
    print(f"Slides: {page}")
    return out_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a walking deck from config + content.")
    parser.add_argument("--config", help="Path to walking-deck-config.json")
    parser.add_argument("--content", help="Override content file path")
    parser.add_argument("--out", help="Override output .pptx path")
    parser.add_argument("--list-blocks", action="store_true", help="List available slide block ids")
    args = parser.parse_args()

    if args.list_blocks:
        print("Available slide blocks:")
        for bid in db.BLOCK_IDS:
            print(f"  - {bid}")
        return
    if not args.config:
        parser.error("--config is required (or use --list-blocks)")
    build(Path(args.config), Path(args.content) if args.content else None, args.out)


if __name__ == "__main__":
    main()
